### ISSUE TITLE
超專業的 maven central 介紹！

### ISSUE THREAD

**Issue by kewang** [shihyuho/jcconf2017-uploading-maven-artifacts#1]
Hi

我這次也有上 [JCConf](http://jcconf.tw/2017/speaker/kewang.html)，講題「如何與全世界分享你的 library」跟你的有點類似，本來也想講一下如何上傳到 maven central 的，不過看了你的這個超完整介紹，我覺得我應該可以著重在其他地方了 XD

**Comment by shihyuho** [comment]
Hello, 我之前有先看了一下你的主題介紹, 沒有留意到會講到上傳這塊, 不好意思耶 :sweat_smile:

**Comment by kewang** [comment]
其實我昨天在還沒看到你的這個 repo 時，還在苦思要如何講這塊比較好。因為步驟實在太多了，而且又繁雜。現在你有講這一塊那我就不用擔心了，哈哈。
